name: Close
on:
  pull_request:
    types: [closed, convert_to_draft]

permissions:
  pull-requests: write

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft != true }}
    steps:
      - name: Assign Reviewer
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels
            for (const name of ["pr review", "ci review", "changes needed"]) {
              if (labels.some(label => label.name === name)) {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  name,
                });
              };
            };
