name: Flakey test
on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  flakey-test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 10 seconds and then fail with a 50% chance
        run: |
          sleep 10
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Failing the test"
            exit 1
          else
            echo "Test passed"
          fi
      - name: Trigger status event externally 
        # GitHub check suites don't trigger workflows on completion, only external
        # suites do. This spoofs an external suite.
        # Note: buildkite reporting success back to github is an external suite.
        run: >-
          curl -L -X POST 
          -H "Content-Type: application/json"
          -H "Authorization: token ${{ secrets.GITHUB_PAT}}"
          -d '{
            "state": "success"
          }'
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/${GITHUB_SHA}"
