name: Assign Reviewer to new PR
on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewer
        uses: actions/github-script@v7
        with:
          script: |
            const { data: { users: requestedReviewers } } = await github.rest.pulls.listRequestedReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            
            if (requestedReviewers.users.length === 0) {
              const { data: members } = await github.rest.teams.listMembersInOrg({
                org: "JuliaLang",
                team_slug: "committers",
                per_page: 100,
              });
              // const member_logins = members.map(member => member.login)
              const member_logins = ["LilithHafner", "LilithHafnerBot"] # TODO use committers in production
              
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                assignees: member_logins[Math.floor(Math.random()*member_logins.length)],
              });
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['pr review'],
              });
            }
